In [ ]:
import numpy as np

In [ ]:
adjacency_matrix = np.array(
[[0,0,1,1,0],
 [1,0,0,0,1],
 [0,0,0,1,0],
 [0,1,0,0,1],
 [0,0,0,1,0]])

In [ ]:
np.divide([1,1,1,1],[.5,.5,.3,.2])

array([2.        , 2.        , 3.33333333, 5.        ])

In [ ]:
def PageRank(alpha,adjacency_matrix,iterations):
  eig_vals,_ = np.linalg.eig(adjacency_matrix)
  k = np.max(eig_vals)
  x = np.zeros(adjacency_matrix.shape[0])
  degree_out = np.sum(adjacency_matrix,axis=1)
  if alpha >= 1/float(k):
    print('Não Converge')
    #return np.nan
  beta = (1-alpha)/adjacency_matrix.shape[0]
  x.fill(beta)
  for i in range(iterations):
    x = np.divide(x,degree_out)
    x = np.matmul(adjacency_matrix.T,x)
    x = x/np.sum(x)
  return x


In [ ]:
alphas = [0.1,0.9]
iterations = [5,10,30]
for a in alphas:
  for i in iterations:
    print("\n a = ",a," iterations = ",i,"\n",PageRank(a,adjacency_matrix,i))


 a =  0.1  iterations =  5 
 [0.09375 0.19375 0.04375 0.38125 0.2875 ]

 a =  0.1  iterations =  10 
 [0.09511719 0.19042969 0.04785156 0.38105469 0.28554687]

 a =  0.1  iterations =  30 
 [0.0952381  0.19047619 0.04761905 0.38095238 0.28571429]
Não Converge

 a =  0.9  iterations =  5 
 [0.09375 0.19375 0.04375 0.38125 0.2875 ]
Não Converge

 a =  0.9  iterations =  10 
 [0.09511719 0.19042969 0.04785156 0.38105469 0.28554687]
Não Converge

 a =  0.9  iterations =  30 
 [0.0952381  0.19047619 0.04761905 0.38095238 0.28571429]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: ComplexWarning: Casting complex values to real discards the imaginary part
  
